[package]
name = "frontend"
version = "0.1.0"
authors = ["b <b@mgmg>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
yew = "0.9.2"
failure = "0.1.5"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
