#!/bin/env bash

port=8001
endpoint=api/add_project
#endpoint=api/add_user
#body="@add_project.json"
ct="application/json"
project_name=$1

body="{\"token\": { \"name\": \"TS\", \"hash\": 666 }, \"project_name\": \"$project_name\" }"

curl -d "$body" -H "Content-Type: $ct" -X POST "127.0.0.1:$port/$endpoint"
echo
