[package]
name = "common"
version = "0.1.0"
authors = ["Brian McClelland"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
erased-serde = { version = "0.3.9" }
diesel = { version = "1.4.2" }
diesel-derive-newtype = "0.1.2"
